In [1]:
import numpy as np
import sympy as sym
import hjson
from pydae.bmapu.bmapu_builder import bmapu
import pydae.build_v2 as db
import pytest
import matplotlib.pyplot as plt
import pydae.ssa as ssa

In [2]:
import temp

model = temp.model()
model.Dt = 0.01
model.decimation = 1

model.ini({'v_f_1':1.0,'p_m_1':0.2},'xy_0.json')
model.ini({'v_f_1':2.8491,'p_m_1':0.8, 'K_delta_0':0.0})

Input or parameter K_delta_0 not found.

True

In [3]:
model.report_x()
model.report_y()
model.report_z()

delta_1 =  0.63
omega_1 =  1.00
e1q_1 =  1.14
e1d_1 =  0.42
e2q_1 =  1.07
e2d_1 =  0.51
V_dummy_2 =  1.00
xi_freq =  0.00
V_1   =  1.00
theta_1 =  0.00
V_2   =  1.00
theta_2 =  0.00
i_d_1 =  0.96
i_q_1 =  0.29
p_g_1 =  0.80
q_g_1 =  0.60
omega_coi =  1.00
p_agc =  0.00
V_1   =  1.00
V_2   =  1.00
p_e_1 =  0.80
v_f_1 =  2.85
V_dummy_2 =  1.00

In [6]:
ssa.A_eval(model)
ssa.damp_report(model).round(2)

         Real  Imag  Freq.  Damp
Mode 1  -0.01  0.00   0.00  1.00
Mode 2 -61.64  0.00   0.00  1.00
Mode 3 -57.15  0.00   0.00  1.00
Mode 4  -1.12  7.84   1.25  0.14
Mode 5  -1.12 -7.84   1.25  0.14
Mode 6  -0.52  0.00   0.00  1.00
Mode 7  -4.67  0.00   0.00  1.00
Mode 8  -1.00  0.00   0.00  1.00

In [5]:
ssa.participation(model).abs().round()

           Mode 1  Mode 2  Mode 3  Mode 4  Mode 5  Mode 6  Mode 7  Mode 8
delta_1       0.0     0.0     0.0     1.0     1.0     0.0     0.0     0.0
omega_1       0.0     0.0     0.0     1.0     1.0     0.0     0.0     0.0
e1q_1         0.0     0.0     0.0     0.0     0.0     1.0     0.0     0.0
e1d_1         0.0     0.0     0.0     0.0     0.0     0.0     1.0     0.0
e2q_1         0.0     0.0     1.0     0.0     0.0     0.0     0.0     0.0
e2d_1         0.0     1.0     0.0     0.0     0.0     0.0     0.0     0.0
V_dummy_2     0.0     0.0     0.0     0.0     0.0     0.0     0.0     1.0
xi_freq       1.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0